In [4]:
import numpy as np

In [5]:
# import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
new = arr.reshape(-1)
print(new)

[1 2 3 4 5 6]


In [7]:
arr = np.array([[[1,2,3],[2,3,4],[3,4,5]]])
for i in np.nditer(arr):
    print(i)

1
2
3
2
3
4
3
4
5


In [11]:
arr = np.array([1,2,3,4,5,6,7,8])
new = np.array_split(arr,4)
print(new[0])


[1 2]


In [12]:
arr = np.array([1,2,3,4,5,6,7,8])
print(np.where(arr == 4))
print(np.where(arr % 2 == 0))


(array([3], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)


In [15]:
arr = np.array([3,1,5,8,7,6,2])
new = np.sort(arr)
print(new)

[1 2 3 5 6 7 8]


In [17]:
n = np.random.randint(100, size = (5))
print("n = ", n)
m = np.random.randint(100, size=(3,5))
print("m = ",m)
z = np.random.choice([1,2,3,4,5])
print("z = ",z)

n =  [76 85 71 40 38]
m =  [[22 88 48 83 39]
 [12 96 18 59 18]
 [48 86 93 77 49]]
z =  5
